import axios from 'axios'

interface GraphTokenResponse {
  access_token: string
  expires_in: number
}

let cachedToken: string | null = null
let tokenExpiry: number = 0

async function getAccessToken(): Promise<string> {
  const now = Date.now()
  if (cachedToken && now < tokenExpiry - 60000) {
    return cachedToken
  }

  const tenantId = process.env.AZURE_TENANT_ID
  const clientId = process.env.AZURE_CLIENT_ID
  const clientSecret = process.env.AZURE_CLIENT_SECRET

  if (!tenantId || !clientId || !clientSecret) {
    throw new Error('Azure AD credentials not configured. Set AZURE_TENANT_ID, AZURE_CLIENT_ID, and AZURE_CLIENT_SECRET in .env.local')
  }

  const tokenUrl = `https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token`
  const params = new URLSearchParams({
    grant_type: 'client_credentials',
    client_id: clientId,
    client_secret: clientSecret,
    scope: 'https://graph.microsoft.com/.default',
  })

  const response = await axios.post<GraphTokenResponse>(tokenUrl, params.toString(), {
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    timeout: 15000,
  })

  cachedToken = response.data.access_token
  tokenExpiry = now + response.data.expires_in * 1000
  return cachedToken
}

export async function sendEmail(
  fromAddress: string,
  toAddress: string,
  subject: string,
  bodyHtml: string
): Promise<void> {
  const token = await getAccessToken()

  const message = {
    subject,
    body: {
      contentType: 'HTML',
      content: bodyHtml,
    },
    toRecipients: [
      {
        emailAddress: {
          address: toAddress,
        },
      },
    ],
  }

  await axios.post(
    `https://graph.microsoft.com/v1.0/users/${fromAddress}/sendMail`,
    { message, saveToSentItems: true },
    {
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      timeout: 15000,
    }
  )
}

export async function sendLowStockEmail(
  fromAddress: string,
  toAddress: string,
  productName: string,
  sku: string,
  currentQty: number,
  reorderPoint: number
): Promise<void> {
  const subject = `[Inventory Alert] Low Stock: ${productName}`
  const body = `
    <html><body style="font-family: Arial, sans-serif; color: #333;">
      <h2 style="color: #e65100;">⚠️ Low Stock Alert</h2>
      <p>The following item has fallen below its reorder point:</p>
      <table style="border-collapse: collapse; width: 400px;">
        <tr style="background:#f5f5f5;"><td style="padding:8px;border:1px solid #ddd;font-weight:bold;">Product</td><td style="padding:8px;border:1px solid #ddd;">${productName}</td></tr>
        <tr><td style="padding:8px;border:1px solid #ddd;font-weight:bold;">SKU</td><td style="padding:8px;border:1px solid #ddd;">${sku}</td></tr>
        <tr style="background:#f5f5f5;"><td style="padding:8px;border:1px solid #ddd;font-weight:bold;">Current Stock</td><td style="padding:8px;border:1px solid #ddd;color:#cc0000;font-weight:bold;">${currentQty}</td></tr>
        <tr><td style="padding:8px;border:1px solid #ddd;font-weight:bold;">Reorder Point</td><td style="padding:8px;border:1px solid #ddd;">${reorderPoint}</td></tr>
      </table>
      <p style="margin-top:20px;">Please review your inventory and place a reorder as soon as possible.</p>
      <hr style="border:none;border-top:1px solid #ddd;margin:20px 0;">
      <p style="font-size:12px;color:#999;">This alert was generated by your Inventory Management System.</p>
    </body></html>
  `
  await sendEmail(fromAddress, toAddress, subject, body)
}
